"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const source = fs.readFileSync(path.resolve(__dirname, "../background.js"), "utf8");
assert.match(source, /const OPEN_SETTLE_MS = 15000/);
assert.match(source, /const ATTACH_SETTLE_MS = 15000/);
assert.match(source, /const SLOT_COOLDOWN_MS = 5000/);
assert.match(source, /const SEQUENCE_ALARM = "mygpt-v4-sequence-step"/);
assert.match(source, /scheduleSequenceAlarm\(token, "OPEN_WAIT", OPEN_SETTLE_MS\)/);
assert.match(source, /scheduleSequenceAlarm\(token, "ATTACH_WAIT", ATTACH_SETTLE_MS\)/);
assert.doesNotMatch(source, /WAIT_COMPLETE/);
assert.match(source, /scheduleSequenceAlarm\(token, "COOLDOWN", SLOT_COOLDOWN_MS\)/);
assert.match(source, /await scheduleAfterSequentialSlot\(token, slot\.slotId\);/);
assert.match(source, /async function attachInMain\(/);
assert.match(source, /async function pasteInMain\(/);
assert.match(source, /chrome\.tabs\.create\(\{ url: sourceIdentity\.workerUrl, active: true \}\)/);
assert.match(source, /await beginNextSequentialSlot\(token\)/);
assert.doesNotMatch(source, /const opened = \[\]/);
console.log("Sequential one-worker-at-a-time orchestration: PASS");
