"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "manifest.json"), "utf8"));
const worker = fs.readFileSync(path.join(root, "service_worker.js"), "utf8");
const popup = fs.readFileSync(path.join(root, "popup.js"), "utf8");
const strategies = fs.readFileSync(path.join(root, "session_strategy.js"), "utf8");
const store = fs.readFileSync(path.join(root, "output_directory_store.js"), "utf8");
const relocator = fs.readFileSync(path.join(root, "output_relocator.js"), "utf8");

assert.equal(manifest.version, "0.5.0");
assert.equal(manifest.name, "MYGPT Worker Orchestrator v5");
assert.match(worker, /background\.js.*output_directory_store\.js.*image_collector\.js.*output_relocator\.js/);
assert.match(strategies, /"fresh-chat"/);
assert.match(strategies, /runMessage: "MYGPT_V4_RUN_THREE"/);
assert.match(strategies, /"branch-thinking"/);
assert.match(strategies, /supported: false/);
assert.match(popup, /preflightOutputDirectoryForRun/);
assert.match(popup, /queryWritePermission\(handle\)/);
assert.match(popup, /requestWritePermission\(handle\)/);
assert.match(popup, /OUTPUT_DIRECTORY_PREFLIGHT_/);
assert.match(popup, /type: currentStrategy\.runMessage/);
const preflightCall = popup.indexOf("await preflightOutputDirectoryForRun();");
const startCall = popup.indexOf("type: currentStrategy.runMessage");
assert.ok(preflightCall >= 0 && startCall > preflightCall, "permission preflight must happen before worker start message");
assert.match(popup, /showDirectoryPicker\(options\)/);
assert.match(popup, /mode: "readwrite"/);
assert.match(popup, /保存先を再許可して保存/);
assert.match(popup, /outputPhase === "PERMISSION_REQUIRED"/);
assert.match(store, /indexedDB\.open/);
assert.match(store, /setDirectoryHandle/);
assert.match(store, /requestWritePermission/);
assert.match(store, /handle\.requestPermission\(\{ mode: "readwrite" \}\)/);
assert.match(relocator, /createWritable\(\)/);
assert.match(relocator, /getFile\(\)/);
assert.match(relocator, /file\.size !== bytes\.byteLength/);
assert.match(relocator, /chrome\.downloads\.removeFile/);
assert.match(relocator, /outputPhase: "DEFAULT_DOWNLOADS"/);
assert.match(relocator, /outputPhase: "PERMISSION_REQUIRED"/);
assert.doesNotMatch(relocator, /chrome\.downloads\.download\(/);
console.log("Worker Orchestrator v5 output preflight + strategy contract: PASS");
