"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const runner = require("../prompt_stacker_runner.js");
assert.equal(typeof runner.createRunController, "function");
assert.equal(typeof runner.waitFor, "function");
assert.equal(typeof runner.createRunner, "function");
const controller = runner.createRunController();
controller.start();
assert.equal(controller.state, "running");
const generation = controller.generation;
assert.equal(controller.canRun(generation), true);
controller.stop();
assert.equal(controller.canRun(generation), false);
const source = fs.readFileSync(path.resolve(__dirname, "../prompt_stacker_runner.js"), "utf8");
assert.match(source, /aria-disabled/);
assert.match(source, /data-disabled/);
assert.match(source, /button\.click\(\)/);
assert.match(source, /allowEnterFallback/);
assert.match(source, /beforeActivate/);
console.log("Translation Loop Prompt Stacker direct reuse: PASS");
