"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "manifest.json"), "utf8"));
const background = fs.readFileSync(path.join(root, "background.js"), "utf8");
const observer = fs.readFileSync(path.join(root, "page_observer.js"), "utf8");
const productFiles = ["manifest.json","background.js","chatgpt_adapter.js","content.js","page_observer.js","popup.js","prompt_stacker_runner.js","loop_core.js","terminal_gate.js","runtime_guard.js","route_adapter.js"];
const source = productFiles.map((name) => fs.readFileSync(path.join(root, name), "utf8")).join("\n");
assert.equal(manifest.version, "0.4.1");
assert.ok(manifest.permissions.includes("alarms"));
assert.equal(manifest.content_scripts[0].world, "MAIN");
assert.deepEqual(manifest.content_scripts[0].js, ["page_observer.js","prompt_stacker_runner.js","chatgpt_adapter.js"]);
assert.ok(background.includes("TranslationLoopRuntimeGuard"));
assert.ok(background.includes("TranslationLoopCore.evaluateSubmissionEvidence"));
assert.ok(background.includes("TranslationLoopTerminalGate.classifyTerminal"));
assert.ok(background.includes('allowEnterFallback: false'));
assert.ok(background.includes('activation !== "native-click"'));
assert.ok(background.includes("chrome.runtime.onConnect"));
assert.ok(background.includes("chrome.alarms.onAlarm"));
const armAt = background.indexOf('MYGPT_V3_ARM_PAGE_OBSERVER');
const clickAt = background.indexOf('runner.clickSend');
assert.ok(armAt >= 0 && clickAt > armAt, "observer must arm before click");
assert.ok(observer.includes("conversation-commit"));
assert.ok(observer.includes("activeConversationNonce"));
assert.ok(observer.includes("ws.chatgpt.com"));
const banned = [/Authorization/i,/\bBearer\b/i,/google-analytics/i,/imgbb/i,/Autojourney/i,/membership/i,/declarativeNetRequest/i,/sendBeacon/i];
for (const pattern of banned) assert.equal(pattern.test(source), false, `banned mechanism: ${pattern}`);
assert.doesNotMatch(background, /requestSubmit\s*\(/);
assert.doesNotMatch(background, /\.submit\s*\(/);
assert.equal((background.match(/chrome\.tabs\.create\s*\(/g) || []).length, 1);
console.log("MYGPT Worker Fanout v4 integration contract: PASS");
