"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const source = fs.readFileSync(path.resolve(__dirname, "../content.js"), "utf8");
assert.match(source, /function isWorkerContext\(\)/);
assert.match(source, /function isContextInvalidatedError\(/);
assert.match(source, /function stopRuntimeBridge\(/);
assert.match(source, /runtimeBridgeDead = true/);
assert.match(source, /observer\.disconnect\(\)/);
assert.match(source, /removeEventListener\(PAGE_OBS_EVENT, onPageObserved\)/);
assert.match(source, /function runtimeBridgeAlive\(/);
assert.match(source, /if \(runtimeBridgeDead \|\| !isWorkerContext\(\) \|\| monitorPort \|\| !runtimeBridgeAlive\(\)\) return;/);
assert.match(source, /if \(isContextInvalidatedError\(error\)\) \{\s*stopRuntimeBridge\(\)/);
console.log("Extension-context invalidation hard stop: PASS");
